export const dataReducer = () => {
  return [
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
    {
      opportunity: "All Fund investment ",
      opportunityState: "Closed",
      target: 5000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: false,
    },
    {
      opportunity: "AIF Fund",
      opportunityState: "Open",
      target: 25000,
      dueDate: "20 Mar 2021",
      stage: "Negotiation",
      clientName: "Chris Ramos",
      clientType: "Prospect",
      fav: true,
    },
  ];
};
